### ISSUE TITLE
Multilingual Site

### ISSUE THREAD

**Issue by vishalbandre** [vishalbandre/php-blog#17]
# Objective: Multilingual Site

### Requirements:
1. Site should be multilingual. Authors should be able to create multilingual content.
2. User should be provided with some kind of switching mechanism to enable the translation or multilingual site.
3. Make available specific language posts based on user preference (user preference to be stored either with cookies or session variable).
4. Authenticated user should be able to add language translations as per their choice. They should be able to edit existing translations.
5. Anonymous users should be able to access the multilingual version based on their choice.
6. Multilingual version should be available on url prefixed with language prefix such as /mr for Marathi, /hi for Hindi and so on.
7. User interface translations should be available in chosen language.
8. Multilingual feature should support RTL (Right to Left) scripts, such as Arabic and Urdu).

### Implementation:
1. User will be provided with functionality to easily enter multilingual content.
2. In the footer bar people will get an option to switch language. Based on available languages and user preference the appropriate translation on the interface as well as articles will be shown.
3. The specific type of language content will be served based on the value set in a session/cookie variable. This session or cookie variable will be set in implementation step number 2
4. To store the translations new database table will be created. The relation between base post to translations will be one-to-many (base post to many translations).
5. Authenticated users will be provided with an option to translate existing posts only. When a user clicks on translate this post, he will be redirected to the post edit form, but, this time based on the chosen translation. (If he tries to translate a post that already exists he will be provided with an edit translation form instead of a creation form). Anonymous users will not be able to see the translate this post button. After completing the post translation creation or edit the data will be stored in a specially created table.
6. When authenticated user clicks on translate button he will be shown a select desired language interface. In this interface we will show him/her a list of language in which he can continue with a translation. The languages shown in this interface will be stored in separate database table. We will pull and show that in user interface.
7. In step 6 & 7, we have created a translation flow and now have translations available. In article view page under post title we will show a little internal navigation to navigate to the available translation view. This navigation will be visible to all the users, authenticated as well as anonymous users.
8. In order to make layout support Right to Left scripts, we will use direction: rtl; property. We will change Title, Description and Body tags to support the right to left direction. Under RTL systems the writing starts from the right of the page and continues to the left, proceeding from top to bottom for new lines. ([RTL Reference 1: Right-to-left Styling - RTL Styling 101](https://rtlstyling.com/posts/rtl-styling), [RTL Reference 2: Structural markup and right-to-left text in HTML](https://www.w3.org/International/questions/qa-html-dir))

**RTL Example:**
Set direction property to right to left like, "direction: rtl;".
<pre>
<div style="direction: rtl;">
صباح الخير
</div>
</pre>

### Database Structure:
// languages table is used to seed the drop-down array only. This array will be used to pre-populate appropriate drop downs, then, the language string will be stored in respective tables. This table is related no-where.
<pre>
create table languages (
    id int not null auto_increment primary key,
    name varchar(100) not null unique,
    prefix varchar(25) not null unique,
    is_default boolean not null default false
);

// We will seed default language manually/installation wizard in languages table.
insert into languages(name, prefix, is_default) values('English', 'en', true);

Other languages can be added from admin interface.
</pre>

<strike>
This table contains all the fields from 'posts' table plus two extra fields to store post reference and also a language. We will retrieve data from these fields based on the url base. (URL base is a prefix based on which we are going to determine the current language. e.g. mr, hi, etc.)
<pre>
create table posts_translations (
    id int not null auto_increment primary key,
    post_id int not null,
    language varchar(25) not null,
    user varchar(25) not null,
    title varchar(200) not null unique,
    description text,
    body text,
    created_at datetime default now(),
    updated_at timestamp not null default current_timestamp on update current_timestamp,
    foreign key (user) references users(username),
    foreign key (post_id) references posts(id)
);
</pre>
</strike>
<hr />

// Altered posts table. This table will contain existing + two new fields post_id & language. We will create a self-referencing foreign
key for post_id field. This way we can relate default language post with its multilingual versions.
<pre>
create table posts (
    id int not null auto_increment primary key,
    base_post_id int not null,
    language_id int not null,
    user varchar(25) not null,
    title varchar(200) not null unique,
    description text,
    body text,
    created_at datetime default now(),
    updated_at timestamp not null default current_timestamp on update current_timestamp,
    foreign key (user) references users(username),
    foreign key (base_post_id) references posts(id),
    foreign key (language_id) references languages(id)
);

// Added fields with alteration
alter table posts add base_post_id int;
ALTER TABLE posts ADD FOREIGN KEY (base_post_id) REFERENCES posts(id);

alter table posts add language_id int;
ALTER TABLE posts ADD FOREIGN KEY (language_id) REFERENCES languages(id);
</pre>

// The "translations" table will be used to store UI translation tokens.
// i) "term" is a token we want to translate.
// ii) "translation" is a translated version of this term.
// iii) "language" is a current language instance for the translated term. We will be using this field to load the appropriate translations based on the URL base. (URL base is a prefix based on which we are going to determine the current language. e.g. mr, hi, etc.)
<pre>
// Previous Approach
// Problem: If we continue with this approach the terms will get duplicated for every new translation.
create table translations (
    id int not null auto_increment primary key,
    term varchar(100) not null unique,
    translation varchar(25) not null unique,
    language_id int not null,
    foreign key (language_id) references languages(id)
);

// Solution:
// Another way with two separate tables for terms and translations and we will relate them such a way that one term can have multiple translations (one to many approach). This way we will remove the redundancy in "terms".
create table terms (
    id int not null auto_increment primary key,
    term varchar(100) not null unique
);

create table translations (
    id int not null auto_increment primary key,
    translation varchar(250) not null,
    term_id int not null,
    language_id int not null,
    foreign key (term_id) references terms(id),
    foreign key (language_id) references languages(id)
);
</pre>

### Files Structure:
**Model files to handle database operations:**
// posts/models/PostTranslation.php - Will house CRUD operations for posts_translations table.
// admin/multilingual/models/Language.php - Will house operations for language table
// admin/multilingual/models/Translation.php - Will store global UI translation CRUD operations. This file will house CRUD operations relating to translations table. This class provides methods for adding new translations, editing and deleting the existing ones.

**Controller Files:**
Language:
// admin/multilingual/langs/create.php, edit.php, delete.php, view.php

Post Translation:
// posts/create.php, delete.php, edit.php

Translation: (UI Translation)
// admin/multilingual/translations/create.php, edit.php, delete.php, view.php

### Routing:
We will make available multilingual version based on url prefix.
E.g.,
http://blog/mr/posts/view/first-post
In this url "mr" is a prefix for language Marathi. We'll achieve this with the help of .htaccess rules. Following rule will give us this structure to access mr as a parameter to take next actions or necessary redirects, etc.
**Multilingual Views**
"RewriteRule ^(.+)/posts/view/(.+)/?$ posts/article.php?slug=$2&lang=$1"
In this rules we are reading first parameter as users desired language version. It'll give us variable $_GET['lang'].

### Progress:
1. Currently, on: Database structure to be finalised.
2. Implementing Language CRUD operations.
3. Upcoming, after Language CRUD operations, next sub-task will be PostTranslation CRUD operations.

### Sub-tasks:
1. Database Structure for Post and UI Translation.
2. Language module: CRUD Operations.
3. Post Translations: Altering Posts module to integrate multilingual feature. 
4. UI Translations
5. Routing setup: .htaccess, navigation, etc.
6. Testing.

### Caching Database Queries with Memcached

Memcached is an in-memory key-value store for small chunks of arbitrary data (strings, objects) from results of database calls, API calls, or page rendering. It's a free & open source, high-performance, distributed memory object caching system.

Setting Memcached on Ubuntu 20.04:
<pre>
sudo apt update
sudo apt install memcached libmemcached-tools

// Start the memcached service
sudo systemctl start memcached

// Install memcached support for php with this module
sudo apt install php-memcached

// Restart the server
sudo systemctl reload apache2

// Testing Memcached
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$mem = new Memcached();
$mem->addServer('127.0.0.1', 11211);
if ($mem->add("success", "Memcached Success!", 600)) {
    echo  'Cached!';
} else {
    echo 'Data: ' . $mem->get("success");
}

// Randomly check for memcache hit
echo 'Data: ' . $mem->get("success");

// Testing for MySQL Server
$database = "php_blog";
$servername = "localhost";
$username = "php_blog_user";
$password = "php_blog_password";
$memtest = new Memcached();
$memtest->addServer("127.0.0.1", 11211); // 11211 is a default memcached port
$conn = new mysqli($servername, $username, $password, $database);
$sql = "SELECT * FROM languages";
$retval = $conn->query($sql);
$result = $retval->fetch_assoc();
$sqlkey = "KEY" . md5($sql);
$memtest->set($sqlkey, $result);
$result2 = $memtest->get($sqlkey);
if ($result2) {
    print "<div>Cached Data: " . $result2['name'] . "</div>";
}

// Testing for Languages Module
$database = "php_blog";
$servername = "localhost";
$username = "php_blog_user";
$password = "php_blog_password";
$memtest = new Memcached();
$memtest->addServer("127.0.0.1", 11211); // 11211 is a default memcached port
$conn = new mysqli($servername, $username, $password, $database);
$sql = "SELECT * FROM languages";
$retval = $conn->query($sql);
</pre>
We can't directly store objects inside memcache. Instead, we can push that database object data row by row inside an array and then we can easily store and retrieve it from memcache object.
<pre>
$data = array();
while($row = $retval->fetch_assoc()) {
    $data[] = $row;
}

$sqlkey = "KEY" . md5($sql);
$memtest->set($sqlkey, $data);
$langs = $memtest->get($sqlkey);

foreach($langs as $lang) {
    echo $lang['name'];
}

</pre>

### Checks for Delete operation in the Language Module:
1. Only admin should be able to delete the language.
2. Language being deleted should not be the default site language. User should not be presented with "Delete" button. Also, users other than admin should not be able to delete this language accessed otherwise, directly from url. We will add extra check on delete page if the current user is an authenticated admin user.
3. Language should not be allowed to delete if it is being referenced by at least one record. Language model will be referenced by "posts" as well as "translations" module. Check should be performed whether the language is free from any locks/references.

### Future Ideas
Admin Dashboard - There are a lot of things we don't require in daily course of actions. But, sometimes we need those features. Like, adding or updating languages, adding or updating new ui elements, taking site in maintenance mode and so on. With admin dashboard we can separate those features from everyday things.

### References:
https://stackoverflow.com/questions/929410/what-are-best-practices-for-multi-language-database-design
https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-memcached-on-ubuntu-20-04
https://linuxize.com/post/how-to-install-memcached-on-ubuntu-20-04/
https://www.cloudways.com/blog/memcached-with-php/
https://memcached.org/
https://en.wikipedia.org/wiki/Memcached
https://rtlstyling.com/posts/rtl-styling
https://www.w3.org/International/questions/qa-html-dir

**Comment by karanvp** [comment]
what a description! never seen before  :1st_place_medal:  @vishalbandre
